# Generated by Django 2.2.6 on 2019-11-25 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fkmanage_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='fkmanage_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='border_loss_cut',
            field=models.FloatField(blank=True, null=True, verbose_name='損切価格'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='border_profit_determination',
            field=models.FloatField(blank=True, null=True, verbose_name='利確価格'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='memo',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='reason_win_loss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.ReasonWinLoss', verbose_name='理由'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Stock', verbose_name='銘柄'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ'),
        ),
    ]
